var team = [
 {real_name:'Borja Salguero [:borjasalguero]', name:'fbsc', email: 'fbsc@tid.es'},
 {real_name:'Nobody', name:'nobody', email: 'nobody@mozilla.org'},
 {real_name:'Andrea Marchesini (:baku)', name:'amarchesini', email: 'amarchesini@mozilla.com'},
 {real_name:'Gregor Wagner [:gwagner]', name:'anygregor', email: 'anygregor@gmail.com'},
 {real_name:'Benjamin Chen', name:'bechen', email: 'bechen@mozilla.com'},
 {real_name:'ben turner [:bent]', name:'bent.mozilla', email: 'bent.mozilla@gmail.com'},
 {real_name:'Brian Smith (:bsmith)', name:'bsmith', email: 'bsmith@mozilla.com'},
 {real_name:'Jet Villegas (:jet)', name:'bugs', email: 'bugs@junglecode.net'},
 {real_name:'Chris Double (:doublec)', name:'chris.double', email: 'chris.double@double.co.nz'},
 {real_name:'Gene Lian [:gene]', name:'clian', email: 'clian@mozilla.com'},
 {real_name:'Chris Peterson (:cpeterson)', name:'cpeterson', email: 'cpeterson@mozilla.com'},
 {real_name:'Cervantes Yu', name:'cyu', email: 'cyu@mozilla.com'},
 {real_name:'Dave Hylands [:dhylands]', name:'dhylands', email: 'dhylands@mozilla.com'},
 {real_name:'Doug Turner (:dougt)', name:'doug.turner', email: 'doug.turner@gmail.com'},
 {real_name:'Donovan Preston', name:'dpreston', email: 'dpreston@mozilla.com'},
 {real_name:'Eric Chou [:ericchou] [:echou]', name:'echou', email: 'echou@mozilla.com'},
 {real_name:'Evelyn Hung [:evelyn]', name:'ehung', email: 'ehung@mozilla.com'},
 {real_name:'Fabrice Desr\xE9 [:fabrice]', name:'fabrice', email: 'fabrice@mozilla.com'},
 {real_name:'Hub Figuiere [:hub]', name:'hub', email: 'hub@mozilla.com'},
 {real_name:'Jose M. Cantera', name:'jmcf', email: 'jmcf@tid.es'},
 {real_name:'Josh Matthews [:jdm]', name:'josh', email: 'josh@joshmatthews.net'},
 {real_name:'Justin Lebar [:jlebar]', name:'justin.lebar+bug', email: 'justin.lebar+bug@gmail.com'},
 {real_name:'Jonathan Watt [:jwatt]', name:'jwatt', email: 'jwatt@jwatt.org'},
 {real_name:'Lawrence Mandel [:lmandel]', name:'lmandel', email: 'lmandel@mozilla.com'},
 {real_name:'Marshall Culpepper [:marshall_law]', name:'marshall', email: 'marshall@mozilla.com'},
 {real_name:'Marco Chen [:mchen]', name:'mchen', email: 'mchen@mozilla.com'},
 {real_name:'Michael Wu [:mwu]', name:'mwu', email: 'mwu@mozilla.com'},
 {real_name:'Brian R. Bondy [:bbondy]', name:'netzen', email: 'netzen@gmail.com'},
 {real_name:'Alexandre Poirot (:ochameau)', name:'poirot.alex', email: 'poirot.alex@gmail.com'},
 {real_name:'Patrick Wang [:kk1fff]', name:'pwang', email: 'pwang@mozilla.com'},
 {real_name:'Randy Lin [:rlin]', name:'rlin', email: 'rlin@mozilla.com'},
 {real_name:'Shih-Chiang Chien [:schien]', name:'schien', email: 'schien@mozilla.com'},
 {real_name:'StevenLee', name:'slee', email: 'slee@mozilla.com'},
 {real_name:'Sean McArthur [:seanmonstar]', name:'smcarthur', email: 'smcarthur@mozilla.com'},
 {real_name:'James Willcox (:snorp) (jwillcox@mozilla.com)', name:'snorp', email: 'jwillcox@mozilla.com'},
 {real_name:'Sta\u015B Ma\u0142olepszy :stas (traveling)', name:'stas', email: 'stas@mozilla.com'},
 {real_name:'Ting-Yuan Huang', name:'thuang', email: 'thuang@mozilla.com'},
 {real_name:'Tim Guan-tin Chien [:timdream] (MoCo-TPE)', name:'timdream+bugs', email: 'timdream+bugs@gmail.com'},
 {real_name:'Thinker Li [:sinker]', name:'tlee', email: 'tlee@mozilla.com'},
 {real_name:'Vincent Chang[:vchang]', name:'vchang', email: 'vchang@mozilla.com'},
 {real_name:'Vicamo Yang [:vicamo][:vyang]', name:'vyang', email: 'vyang@mozilla.com'},
 {real_name:'Vivien Nicolas (:vingtetun)', name:'21', email: ' 21@vingtetun.org '},
 {real_name:'Alberto Pastor', name:'alberto.pastor', email: 'alberto.pastor@o2.com'},
 {real_name:'Alive Kuo [:alive]', name:'alive', email: 'alive@mozilla.com'},
 {real_name:'Brendan Dahl', name:'bdahl', email: 'bdahl@mozilla.com'},
 {real_name:'Ben Francis [:benfrancis]', name:'ben', email: 'ben@krellian.com'},
 {real_name:'Andrew Sutherland (:asuth)', name:'bugmail', email: 'bugmail@asutherland.org'},
 {real_name:'Cody Brocious [:Daeken]', name:'cbrocious', email: 'cbrocious@mozilla.com'},
 {real_name:'Dale Harvey (:daleharvey)', name:'dale', email: 'dale@arandomurl.com'},
 {real_name:'David Flanagan [:djf]', name:'dflanagan', email: 'dflanagan@mozilla.com'},
 {real_name:'Dominic Kuo [:dkuo]', name:'dkuo', email: 'dkuo@mozilla.com'},
 {real_name:'David Scravaglieri [:scravag]', name:'dscravaglieri', email: 'dscravaglieri@mozilla.com'},
 {real_name:'Edwin Flores [:eflores] [:edwin]', name:'eflores', email: 'eflores@mozilla.com'},
 {real_name:'Etienne Segonzac (:etienne)', name:'etienne', email: 'etienne@segonzac.info'},
 {real_name:'Julien Wajsberg [:julienw]', name:'felash', email: 'felash@gmail.com'},
 {real_name:'Fernando Jim\xE9nez Moreno [:ferjm]', name:'ferjmoreno', email: 'ferjmoreno@gmail.com'},
 {real_name:'Fernando Campo (:fcampo)', name:'fernando.campo', email: 'fernando.campo@o2.com'},
 {real_name:'Francisco Jordano [:arcturus]', name:'francisco.jordano', email: 'francisco.jordano@o2.com'},
 {real_name:'Fernando R. Sela [:frsela]', name:'frsela', email: 'frsela@tid.es'},
 {real_name:'Geo Mealer [:geo]', name:'gmealer', email: 'gmealer@mozilla.com'},
 {real_name:'Gregory Szorc [:gps]', name:'gps', email: 'gps@mozilla.com'},
 {real_name:'German', name:'gtorodelvalle', email: 'gtorodelvalle@gmail.com'},
 {real_name:'Gina Yeh', name:'gyeh', email: 'gyeh@mozilla.com'},
 {real_name:'Jason Duell (:jduell)', name:'jduell.mcbugs', email: 'jduell.mcbugs@gmail.com'},
 {real_name:'John Ford [:jhford]', name:'jhford', email: 'jhford@mozilla.com'},
 {real_name:'James Lal [:lightsofapollo] (PTO back nov 27th)', name:'jlal', email: 'jlal@mozilla.com'},
 {real_name:'John O\'Duinn [:joduinn]', name:'joduinn', email: 'joduinn@mozilla.com'},
 {real_name:'Jonas Sicking (:sicking)', name:'jonas', email: 'jonas@sicking.cc'},
 {real_name:'Fabien Cazenave [:kaze]', name:'kaze', email: 'kaze@mozilla.com'},
 {real_name:'Kyle Huey [:khuey] (khuey@mozilla.com)', name:'khuey', email: 'khuey@mozilla.com'},
 {real_name:'Axel Hecht [:Pike]', name:'l10n', email: 'l10n@mozilla.com'},
 {real_name:'mbarone', name:'mbarone976', email: ' mbarone976@gmail.com '},
 {real_name:'Marty Rosenberg [:mjrosenb]', name:'mrosenberg', email: 'mrosenberg@mozilla.com'},
 {real_name:'Philipp von Weitershausen [:philikon]', name:'philipp', email: 'philipp@weitershausen.de'},
 {real_name:'Paul Theriault [:pauljt]', name:'ptheriault', email: ' ptheriault@mozilla.com '},
 {real_name:'Ran Ben Aharon (everything.me)', name:'ran', email: 'ran@doat.com'},
 {real_name:'Rudy Lu [:rudyl]', name:'rlu', email: 'rlu@mozilla.com'},
 {real_name:'Steve Chung', name:'schung', email: 'schung@mozilla.com'},
 {real_name:'Scott Johnson (:jwir3)', name:'sjohnson', email: 'sjohnson@mozilla.com'},
 {real_name:'Jim Porter (:squib)', name:'squibblyflabbetydoo', email: 'squibblyflabbetydoo@gmail.com'},
 {real_name:'Anthony Jones (:kentuckyfriedtakahe)', name:'ajones', email: 'ajones@mozilla.com'},
 {real_name:'Emmanuele Bassi (:ebassi)', name:'ebassi', email: 'ebassi@mozilla.com '},
 {real_name:'Jos\xE9 Antonio Olivera Ortega [:jaoo]', name:'josea.olivera', email: 'josea.olivera@gmail.com'},
 {real_name:'Matthew Gregan [:kinetik]', name:'kinetik', email: 'kinetik@flim.org'},
 {real_name:'Les Orchard [:lorchard]', name:'lorchard', email: 'lorchard@mozilla.com'},
 {real_name:'Michal Budzynski (:michalbe)', name:'mbudzynski', email: 'mbudzynski@mozilla.com'},
 {real_name:'Blake Kaplan (:mrbkap)', name:'mrbkap', email: 'mrbkap@gmail.com'},
 {real_name:'Timothy Nikkel (:tn)', name:'tnikkel', email: 'tnikkel@gmail.com'},
 {real_name:'Tim Taubert [:ttaubert]', name:'ttaubert', email: 'ttaubert@mozilla.com'},
 {real_name:'Victoria Gerchinhoren', name:'vpg', email: 'vpg@tid.es'},
 {real_name:'Yuren Ju [:yurenju]', name:'yurenju', email: 'yurenju@gmail.com'},
 {real_name:'Chuck Lee [:chucklee]', name:'chulee', email: 'chulee@mozilla.com'},
 {real_name:'Chiajung Hung [:chiajung]', name:'chung', email: 'chung@mozilla.com'},
 {real_name:'David Baron [:dbaron]', name:'dbaron', email: 'dbaron@dbaron.org'},
 {real_name:'Josh Carpenter [:jcarpenter]', name:'jcarpenter', email: 'jcarpenter@mozilla.com'},
 {real_name:'Kevin Grandon', name:'kgrandon', email: 'kgrandon@mozilla.com'},
 {real_name:'Larissa Co', name:'lco', email: 'lco@mozilla.com'},
 {real_name:'Margaret Leibovic [:margaret]', name:'margaret.leibovic', email: 'margaret.leibovic@gmail.com'},
 {real_name:'Matt Woodrow (:mattwoodrow)', name:'matt.woodrow', email: 'matt.woodrow@gmail.com'},
 {real_name:'KM Lee [:rexboy]', name:'rexboy', email: 'rexboy@mozilla.com'},
 {real_name:'Salvador de la Puente Gonz\xE1lez [:salva]', name:'salva', email: 'salva@unoyunodiez.com'},
 {real_name:'Ian Liu [:ianliu]', name:'iliu', email: 'iliu@mozilla.com'},
 {real_name:'Marco Castelluccio [:marco]', name:'mar.castelluccio', email: 'mar.castelluccio@studenti.unina.it'},
 {real_name:'Mike Habicher [:mikeh]', name:'mhabicher', email: 'mhabicher@mozilla.com'},
 {real_name:'Thomas Zimmermann', name:'tzimmermann', email: 'tzimmermann@mozilla.com'},
 {real_name:'Jeff Gilbert [:jgilbert]', name:'jgilbert', email: 'jgilbert@mozilla.com'},
 {real_name:'Carmen Jim\xE9nez Cabezas', name:'macajc', email: 'macajc@gmail.com'},
 {real_name:'Jeff Hammel [:jhammel]', name:'jhammel', email: 'jhammel@mozilla.com'},
 {real_name:'Marijn Haverbeke', name:'marijnh', email: 'marijnh@gmail.com'},
 {real_name:'Shelly Lin [:shelly]', name:'slin', email: 'slin@mozilla.com'},
 {real_name:'Patryk Adamczyk [:patryk] UX', name:'padamczyk', email: 'padamczyk@mozilla.com'}
]
